/* eslint-disable */ /**
 *
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
 *
 * instead, edit one of the `.graphql` files in this project and run
 *
 * npm run graphql:codegen
 *
 * for this file to be re-created
 */

import * as Types from '../../../init/graphql/types.generated.js';

module.hot?.accept();
export type GetArticlesQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type GetArticlesQuery = { articles?: { data: Array<{ attributes?: { title?: string | null } | null }> } | null };
